### ISSUE TITLE
Memory check fails on MacOS

### ISSUE THREAD

**Issue by techdragon** [LuisAlejandro/pypicontents#21]
```
Traceback (most recent call last):
  File "/Users/techdragon/.local/venvs/pypicontents/lib/python2.7/site-packages/pypicontents/cli.py", line 241, in main
    status = args.command(**vars(args))
  File "/Users/techdragon/.local/venvs/pypicontents/lib/python2.7/site-packages/pypicontents/api/pypi.py", line 381, in pypi
    mem_available = int(get_free_memory())
  File "/Users/techdragon/.local/venvs/pypicontents/lib/python2.7/site-packages/pypicontents/core/utils.py", line 48, in get_free_memory
    with open('/proc/meminfo', 'r') as memory:
IOError: [Errno 2] No such file or directory: '/proc/meminfo'
```
Should be fairly easy to find a workaround. Just need a MacOS way to get the memory info and the rest of the logic should be the same.

**Comment by LuisAlejandro** [comment]
Thaks for reporting. I'll take a look as soon as I can.
